# Site settings
title: jdroid Home
description: JDroid의 홈페이지 입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.jdroid.ml" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jdroid
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Android Developer
email: wonjin2168@gamil.com
linked_username: wonjin2168
github_username:  jdroid-git
gplus_username:  wonjin2168

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
